### ISSUE TITLE
Status of the package?

### ISSUE THREAD

**Issue by srsidd** [ros-industrial-consortium/packml#26]
What is the status of this package right now? 
Would you recommend using the ROS-I packml as an alternative for SMACH at this point of time? 
I don't see a lot of documentation (How to use, tutorials, when this is production ready etc). 
Any information will be useful! Thanks.

**Comment by shaun-edwards** [comment]
We are continuing to develop this package.  We plan to use this package at PlusOne and there are other Institutions that have expressed interest.  Documentation and tutorials are missing.

Unless you have a specific interest in PackML, I would recommend SMACH.  It's well documented, and easier to use.

**Comment by srsidd** [comment]
Awesome, thanks!
