### ISSUE TITLE
packml_sm Qt dependency not captured

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/packml#7]
When depending on the `packml_sm` package, the lines below must be added to the `CMakeLists.txt` in order to build/include headers.  The CMake logic is complicated by Qt4/5 support, but the dependency should be captured in the packml_sm package, with no requirement on downstream packages.

```
if("${qt_gui_cpp_USE_QT_MAJOR_VERSION} " STREQUAL "5 ")
  find_package(Qt5Widgets REQUIRED)
else()
  find_package(Qt4 COMPONENTS QtCore QtGui REQUIRED)
  include(${QT_USE_FILE})
endif()
```

**Comment by AustinDeric** [comment]
Which QT version would you like to use?

**Comment by shaun-edwards** [comment]
No longer an issue due to #35
